name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Diperlukan untuk commit folder android

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      env:
        NODE_OPTIONS: --max-old-space-size=4096

    - name: Generate package-lock.json
      run: |
        if [ ! -f package-lock.json ]; then
          npm install --package-lock-only
        fi

    - name: Initialize React Native Android project
      run: |
        if [ ! -d android ]; then
          npx react-native@0.72.0 init TempProject --skip-install
          mv TempProject/android .
          rm -rf TempProject
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add android
          git commit -m "Add android folder for React Native build" || echo "No changes to commit"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Android SDK
      uses: actions/cache@v3
      with:
        path: ~/.android
        key: android-sdk-${{ hashFiles('**/android/build.gradle') }}
        restore-keys: android-sdk-

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2

    - name: Build APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleRelease --stacktrace

    - name: Check APK
      run: |
        ls -l android/app/build/outputs/apk/release/app-release-unsigned.apk
        if [ ! -f "android/app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
          echo "APK file not found!"
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
        if-no-files-found: error